# 新版本Compose已弃用version字段

services:
  postgres:
    image: postgres:16
    container_name: nkuwiki_db
    networks:
      - nkuwiki-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro,z
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nkuwiki_user -d nkuwiki_db"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ./ETL/wechat
      dockerfile: Dockerfile
    container_name: wechat_importer
    networks:
      - nkuwiki-net
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - wechat_data:/data/wechat
      - ./ETL/wechat/.env:/app/.env:ro
    environment:
      DATABASE_URL: postgresql://${DB_USER:-nkuwiki_user}:${DB_PASSWORD:-123456}@postgres:5432/${DB_NAME:-nkuwiki_db}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-nkuwiki_user} -d ${DB_NAME:-nkuwiki_db}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - ./ETL/wechat/.env

  verifier:
    build:
      context: ./ETL/wechat
      dockerfile: Dockerfile
    networks:
      - nkuwiki-net
    depends_on:
      app:
        condition: service_started
    command: ["python", "verify_import.py"]

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/postgres
  wechat_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/wechat

networks:
  nkuwiki-net:
    driver: bridge
    attachable: true 