services:
    api_main:
        build: .
        command: python app.py --api --port 8000
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - /data/raw:/app/data/raw
            - /data/models:/app/data/models
        networks:
            - nkuwiki_net
        environment:
            - ENV=main

    api_dev:
        build: .
        command: python app.py --api --port 8001
        ports:
            - "8001:8001"
        volumes:
            - .:/app
            - /data/raw:/app/data/raw
            - /data/models:/app/data/models
        networks:
            - nkuwiki_net
        environment:
            - ENV=dev

networks:
    nkuwiki_net:
        external:
            name: nkuwiki_nkuwiki_net

volumes:
  es_data:
  mysql_data:
  redis_data:
  qdrant_data: 