services:
    elasticsearch:
        image: elasticsearch:8.16.1
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        volumes:
            - /data/elasticsearch:/usr/share/elasticsearch/data
            - ./etl/utils/dictionary:/usr/share/elasticsearch/config/analysis-ik/
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - nkuwiki_net
        command: >
            sh -c "
            if [ ! -d /usr/share/elasticsearch/plugins/analysis-ik ]; then
              echo 'Installing IK Analysis plugin...';
              bin/elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.16.1;
            fi;
            exec /usr/local/bin/docker-entrypoint.sh;
            "

    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - /data/qdrant:/qdrant/storage
        networks:
            - nkuwiki_net

    mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - /data/mysql:/var/lib/mysql
        networks:
            - nkuwiki_net

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - /data/redis:/data
        networks:
            - nkuwiki_net

networks:
    nkuwiki_net:
        driver: bridge 