services:
    api:
        build: .
        command: python app.py --api --port ${API_PORT:-8000}
        ports:
            - "${API_PORT:-8000}:${API_PORT:-8000}"
        volumes:
            - .:/app
            - /data/raw:/app/data/raw
            - /data/models:/app/data/models
        networks:
            - nkuwiki_net
        environment:
            - ENV=${BRANCH:-main}
            - API_PORT=${API_PORT:-8000}
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_USER=${MYSQL_USER}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - DB_NAME=${MYSQL_DATABASE}
            - REDIS_HOST=redis
            - QDRANT_URL=http://qdrant:6333
            - ES_HOST=elasticsearch
            - ELASTICSEARCH_HOST=elasticsearch

networks:
    nkuwiki_net:
        external: true

volumes:
  es_data:
  mysql_data:
  redis_data:
  qdrant_data: 