# 新版本Compose已弃用version字段

services:
  postgres:
    image: registry.cn-hangzhou.aliyuncs.com/library/postgres:15
    platform: linux/amd64
    pull_policy: always
    container_name: nkuwiki_db
    networks:
      - nkuwiki-net
    environment:
      POSTGRES_USER: ${DB_USER:-nkuwiki_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-nkuwiki_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-nkuwiki_user} -d ${DB_NAME:-nkuwiki_db}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    # x-aliyun-mirror: &aliyun-mirror
    #   registry: egi52z78.mirror.aliyuncs.com

  importer:
    build:
      context: ./ETL/wechat
      dockerfile: Dockerfile
    container_name: wechat_importer
    networks:
      - nkuwiki-net
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - wechat_data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB

volumes:
  postgres_data:
    driver: local
  wechat_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/wechat/202501

networks:
  nkuwiki-net:
    driver: bridge
    attachable: true 