CREATE TABLE IF NOT EXISTS `wechat_nku` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `url` varchar(255) NOT NULL COMMENT '文章URL',
    `title` varchar(255) NOT NULL COMMENT '标题',
    `content` text NOT NULL COMMENT '内容',
    `account` varchar(64) NOT NULL COMMENT '公众号账号',
    `account_name` varchar(64) NOT NULL DEFAULT '' COMMENT '公众号名称',
    `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
    `images` json DEFAULT NULL COMMENT '图片列表',
    `view_count` int(11) NOT NULL DEFAULT '0' COMMENT '阅读数',
    `like_count` int(11) NOT NULL DEFAULT '0' COMMENT '点赞数',
    `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_url` (`url`),
    KEY `idx_account` (`account`),
    KEY `idx_publish_time` (`publish_time`),
    FULLTEXT KEY `ft_content` (`content`, `title`) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='南开大学微信公众号文章表'; 