CREATE TABLE IF NOT EXISTS `wxapp_comments` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `post_id` BIGINT NOT NULL COMMENT '帖子ID',
    `openid` VARCHAR(100) NOT NULL COMMENT '评论用户openid',
    `nick_name` VARCHAR(100) DEFAULT NULL COMMENT '用户名称',
    `avatar` VARCHAR(500) DEFAULT NULL COMMENT '用户头像URL',
    `content` TEXT NOT NULL COMMENT '评论内容',
    `parent_id` BIGINT DEFAULT NULL COMMENT '父评论ID（回复）',
    `images` JSON DEFAULT '[]' COMMENT '图片列表',
    `like_count` INT DEFAULT 0 COMMENT '点赞数',
    `liked_users` JSON DEFAULT '[]' COMMENT '点赞用户列表',
    `extra` JSON DEFAULT NULL COMMENT '扩展字段，存储额外信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `platform` VARCHAR(20) DEFAULT 'wxapp' COMMENT '平台标识',
    `status` TINYINT DEFAULT 1 COMMENT '状态：1-正常, 0-禁用',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除：1-已删除, 0-未删除',
    PRIMARY KEY (`id`),
    KEY `idx_post_id` (`post_id`),
    KEY `idx_openid` (`openid`),
    KEY `idx_parent_id` (`parent_id`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_status` (`status`, `is_deleted`),
    FULLTEXT KEY `ft_content` (`content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信小程序评论数据表'; 