CREATE TABLE IF NOT EXISTS `wxapp_notification` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `openid` VARCHAR(100) NOT NULL COMMENT '接收者openid',
    `title` VARCHAR(255) NOT NULL COMMENT '通知标题',
    `content` TEXT NOT NULL COMMENT '通知内容',
    `type` VARCHAR(20) NOT NULL DEFAULT 'system' COMMENT '通知类型: system-系统通知, like-点赞, comment-评论, follow-关注',
    `is_read` BOOLEAN DEFAULT FALSE COMMENT '是否已读',
    `sender` JSON DEFAULT NULL COMMENT '发送者信息',
    `target_id` INT DEFAULT NULL COMMENT '目标ID，如帖子ID、评论ID等',
    `target_type` VARCHAR(20) DEFAULT NULL COMMENT '目标类型，如post, comment等',
    `extra_data` JSON DEFAULT NULL COMMENT '额外数据',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1-正常, 0-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_openid` (`openid`),
    KEY `idx_type` (`type`),
    KEY `idx_is_read` (`is_read`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信小程序通知数据表';