CREATE TABLE IF NOT EXISTS `wxapp_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `openid` VARCHAR(100) NOT NULL COMMENT '微信用户唯一标识',
    `nickname` VARCHAR(100) DEFAULT NULL COMMENT '用户昵称',
    `avatar` VARCHAR(500) DEFAULT NULL COMMENT '头像URL',
    `unionid` VARCHAR(100) DEFAULT NULL COMMENT '微信开放平台唯一标识',
    `gender` TINYINT DEFAULT 0 COMMENT '性别：0-未知, 1-男, 2-女',
    `bio` VARCHAR(255) DEFAULT NULL COMMENT '用户个人简介',
    `country` VARCHAR(50) DEFAULT NULL COMMENT '国家',
    `province` VARCHAR(50) DEFAULT NULL COMMENT '省份',
    `city` VARCHAR(50) DEFAULT NULL COMMENT '城市',
    `language` VARCHAR(20) DEFAULT NULL COMMENT '语言',
    `birthday` VARCHAR(20) DEFAULT NULL COMMENT '生日',
    `wechatId` VARCHAR(50) DEFAULT NULL COMMENT '微信号',
    `qqId` VARCHAR(20) DEFAULT NULL COMMENT 'QQ号',
    `token_count` INT DEFAULT 0 COMMENT '用户Token数量',
    `like_count` INT DEFAULT 0 COMMENT '获得的点赞数',
    `favorite_count` INT DEFAULT 0 COMMENT '获得的收藏数',
    `post_count` INT DEFAULT 0 COMMENT '发布的帖子数',
    `follower_count` INT DEFAULT 0 COMMENT '关注者数量',
    `following_count` INT DEFAULT 0 COMMENT '关注的用户数量',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `last_login` DATETIME DEFAULT NULL COMMENT '最后登录时间',
    `status` TINYINT DEFAULT 1 COMMENT '状态：1-正常, 0-禁用',
    PRIMARY KEY (`id`),
    UNIQUE KEY `unq_openid` (`openid`),
    KEY `idx_unionid` (`unionid`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_status` (`status`),
    KEY `idx_nickname` (`nickname`(20))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信小程序用户数据表'; 