CREATE TABLE IF NOT EXISTS `wxapp_feedback` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `openid` VARCHAR(100) NOT NULL COMMENT '用户openid',
    `content` TEXT DEFAULT NULL COMMENT '反馈内容',
    `type` VARCHAR(20) DEFAULT NULL COMMENT '反馈类型: bug-问题反馈, suggestion-建议, other-其他',
    `contact` VARCHAR(100) DEFAULT NULL COMMENT '联系方式',
    `image` JSON DEFAULT NULL COMMENT '图片URL列表',
    `device_info` JSON DEFAULT NULL COMMENT '设备信息',
    `status` VARCHAR(20) DEFAULT 'pending' COMMENT '反馈状态：pending-待处理, processing-处理中, resolved-已解决, rejected-已拒绝',
    `admin_reply` TEXT DEFAULT NULL COMMENT '管理员回复',
    `admin_id` VARCHAR(100) DEFAULT NULL COMMENT '处理管理员ID',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_openid` (`openid`),
    KEY `idx_type` (`type`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`),
    FULLTEXT KEY `ft_content` (`content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信小程序反馈数据表'; 