CREATE TABLE IF NOT EXISTS `wxapp_posts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `openid` VARCHAR(100) NOT NULL COMMENT '发布用户openid',
    `nick_name` VARCHAR(100) DEFAULT NULL COMMENT '用户名称',
    `avatar` VARCHAR(500) DEFAULT NULL COMMENT '用户头像URL',
    `content` TEXT COMMENT '帖子内容',
    `title` VARCHAR(255) DEFAULT NULL COMMENT '帖子标题',
    `images` JSON DEFAULT '[]' COMMENT '图片列表',
    `tags` JSON DEFAULT '[]' COMMENT '标签列表',
    `category_id` INT DEFAULT NULL COMMENT '分类ID',
    `location` VARCHAR(255) DEFAULT NULL COMMENT '位置信息',
    `view_count` INT DEFAULT 0 COMMENT '浏览量',
    `like_count` INT DEFAULT 0 COMMENT '点赞数',
    `liked_users` JSON DEFAULT '[]' COMMENT '点赞用户列表',
    `favorite_users` JSON DEFAULT '[]' COMMENT '收藏用户列表',
    `comment_count` INT DEFAULT 0 COMMENT '评论数',
    `favorite_count` INT DEFAULT 0 COMMENT '收藏数量',
    `extra` JSON DEFAULT NULL COMMENT '扩展字段，存储额外信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `platform` VARCHAR(20) DEFAULT 'wxapp' COMMENT '平台标识',
    `status` TINYINT DEFAULT 1 COMMENT '状态：1-正常, 0-禁用',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除：1-已删除, 0-未删除',
    PRIMARY KEY (`id`),
    KEY `idx_openid` (`openid`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_platform` (`platform`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_status` (`status`, `is_deleted`),
    FULLTEXT KEY `ft_content` (`title`, `content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信小程序帖子数据表'; 