CREATE TABLE IF NOT EXISTS `wxapp_comment` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `post_id` bigint(20) DEFAULT NULL COMMENT '帖子ID',
    `parent_id` bigint(20) DEFAULT NULL COMMENT '父评论ID',
    `openid` varchar(64) NOT NULL COMMENT '用户openid',
    `nickname` varchar(64) DEFAULT NULL COMMENT '用户昵称',
    `avatar` varchar(255) DEFAULT NULL COMMENT '用户头像',
    `content` text DEFAULT NULL COMMENT '评论内容',
    `image` json DEFAULT NULL COMMENT '图片列表',
    `like_count` int(11) DEFAULT '0' COMMENT '点赞数',
    `reply_count` int(11) DEFAULT '0' COMMENT '回复数',
    `status` tinyint(4) DEFAULT '1' COMMENT '状态：1-正常, 0-禁用',
    `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_post_id` (`post_id`),
    KEY `idx_parent_id` (`parent_id`),
    KEY `idx_openid` (`openid`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_status` (`status`),
    FULLTEXT KEY `ft_content` (`content`) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序评论表';