CREATE TABLE IF NOT EXISTS `wxapp_notification` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `receiver_id` BIGINT NOT NULL COMMENT '接收者用户ID',
    `sender_id` BIGINT DEFAULT NULL COMMENT '发送者用户ID, NULL表示系统',
    `title` VARCHAR(255) DEFAULT NULL COMMENT '通知标题',
    `content` TEXT DEFAULT NULL COMMENT '通知内容',
    `type` VARCHAR(20) DEFAULT 'system' COMMENT '通知类型: system, like, comment, follow',
    `is_read` BOOLEAN DEFAULT FALSE COMMENT '是否已读',
    `target_id` VARCHAR(100) DEFAULT NULL COMMENT '目标ID, 如帖子ID、评论ID等',
    `target_type` VARCHAR(20) DEFAULT NULL COMMENT '目标类型, 如post, comment等',
    `extra_data` JSON DEFAULT NULL COMMENT '额外数据',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `status` TINYINT DEFAULT 1 COMMENT '状态: 1-正常, 0-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_receiver_id` (`receiver_id`),
    KEY `idx_sender_id` (`sender_id`),
    KEY `idx_type` (`type`),
    KEY `idx_is_read` (`is_read`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_status` (`status`),
    FOREIGN KEY (`receiver_id`) REFERENCES `wxapp_user`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`sender_id`) REFERENCES `wxapp_user`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信小程序通知数据表';